### ISSUE TITLE
No way to Authorise Craft, have to manually add access tokern

### ISSUE THREAD

**Issue by studiosyntax** [scaramangagency/craftagram#26]
After entering and saving the App ID and App Secret, both by environment variables, I do not get the "Authorise Craft" button, just a Save button. Therefor I have to generate a token in Instagram Basic Display - Basic Display page.

When I try to save that access token manually on production, I get a server error which seems to be about `allowAdminChanges` set to false. 

Am I doing anything wrong in the workflow?
I can save the token locally and push the update to production but I get the feeling something's wrong.

Craft 3.4.27
Craftagram 1.2.4

**Comment by joshua-martin** [comment]
Sorry about that @studiosyntax –we had a conditional that was checking `APP_ID` was set to 15 characters before it would show the Authorise Craft button, but since we've added the option to add this as an env var, this can obviously be less than 15 characters.

I've removed this limit for you now, so the button should be showing for you, if you update to 1.2.5. I'll leave this token open if you could confirm if this fixes for you.

**Comment by studiosyntax** [comment]
Hey thanks for the quick reply. I can't seem to update to 1.2.5, should I use a non-pushed version or something special?

**Comment by joshua-martin** [comment]
Should be available now. If it doesn’t pull into Craft straight away you can increment your version in composer to 1.2.5 manually.

**Comment by studiosyntax** [comment]
Thanks, it's there. Will report back asap!
