### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by stappjno** [scaramangagency/craftagram#36]
We use CraftCMS just as data source for headless frontends. Is there a way to access the grabbed instagram data via GraphQL or any other kind of API after the plugin got them?

**Comment by joshua-martin** [comment]
This is now available via `/actions/craftagram/default/api`.

It will return the raw JSON data from instagram. You can pass the following parameters:

| URL Parameter | Description |
| --- | --- |
| limit | The default limit from instagram is 25 |
| siteId | The current site's ID. If you only have one site on your install you can leave this blank, otherwise pass the `siteId` for the site you have added the authorisation to. You can hard-code the site ID if you have only set up authorisation on one of your multi-site installs, otherwise pass the current `siteId` dynamically |
| url | Pass the `after` or `before` parameters from `data->paging->cursors` to get the next or the previous set of results |
