### ISSUE TITLE
No valid scopes requested

### ISSUE THREAD

**Issue by thunder87** [scaramangagency/craftagram#57]
Plugin stopped working, getting a **"No valid scopes requested"** error, when authenticating agains instragram.

Url
```
https://www.instagram.com/oauth/authorize?client_id=xxxxxxx&scope=user_profile,user_media&response_type=code&redirect_uri=https://xxxxxx.com/actions/craftagram/default/auth&state=9
```
Response
```
"error_type": "OAuthException", "code": 400, "error_message": "No valid scopes requested"
```

Craft CMS 3.7.52
Craftagram 1.4.5

**Comment by joshua-martin** [comment]
@thunder87 unfortunately this points to an issue with your setup. I can only presume that your setup has changed since you initially completed up your integration. Any errors that  you see when you hit the authenticate button are rendered by Instagram and are as such an issue with setup their end, rather than anything to do with the plugin. 

I had seen this before as per #20, a different error message but same concept.

**Comment by Natetronn** [comment]
FWIW, I ran into this on Brave, but Firefox was working fine? I thought that odd. That's when I realized I was using a different accounts between the two browsers. Once I switched accounts in Instagram, to the account that had the tester logged in, it worked fine again with no error.
